# Generated by Django 3.1.5 on 2021-01-25 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dishes.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dishes.order')),
            ],
        ),
    ]
