# Generated by Django 3.1.5 on 2021-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
